name: "Sync KAPLAYGROUND"

on:
  workflow_dispatch:

jobs:
  sync:
    permissions: write-all
    name: "Sync KAPLAYGROUND"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
            # required
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.BOT_TOKEN }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
            GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
            git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
            git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
   

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: "chore: bump repo"
          signoff: false
          branch: example-patches
          delete-branch: true
          title: "chore: bump repo"
          reviewers: lajbel
          body: "ohhi"
